<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 3,
                'name' => 'User-Owner',
                'email' => 'owner@gmail.com',
                'username' => 'user-owner',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-08-21 03:25:52',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2022-01-01',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '3524111233144330001',
                'city' => 'JAKARTA',
                'employee_id' => '20210101OWN',
                'photo' => 'man.png',
                'photo_netizen_id' => 'draft_netizen_01.jpg',
                'job_id' => 3,
                'branch_id' => 1,
                'department_id' => 6,
                'referral_id' => NULL,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            1 => 
            array (
                'id' => 1,
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'username' => 'admin',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-05-28 12:40:11',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2020-01-01',
                'join_years' => 2,
                'gender' => 'Male',
                'netizen_id' => '3524111233144330001',
                'city' => 'JAKARTA',
                'employee_id' => '20210101ADM',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'user-13.jpg',
                'job_id' => 6,
                'branch_id' => 2,
                'department_id' => 5,
                'referral_id' => NULL,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            2 => 
            array (
                'id' => 26,
                'name' => 'Test User',
                'email' => 'purnomo.yogiaditya@gmail.com',
                'username' => 'test_123',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bIEbT.3PQ4tHVbn9St.oreO5diYJGTV6TqNuWmgGqE8wScBqIxO1S',
                'remember_token' => NULL,
                'created_at' => '2022-07-12 06:19:07',
                'updated_at' => '2022-07-12 08:02:57',
                'phone_no' => '085746879090',
                'address' => 'Lmg',
                'join_date' => '2013-07-11',
                'join_years' => 9,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Lmg',
                'employee_id' => '20000109YG',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 3,
                'branch_id' => 2,
                'department_id' => 2,
                'referral_id' => 3,
                'birth_place' => 'test',
                'birth_date' => '2022-07-03',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            3 => 
            array (
                'id' => 32,
                'name' => 'Jemm Rakar-Terapist',
                'email' => 'jemm@gmail.com',
                'username' => 'jem',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DtwhuxLX7GD5Mkcdtk3nK.9D.shExDpmeqeNaffU.KOTnAKhPmRrS',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 08:09:55',
                'updated_at' => '2022-07-30 08:09:55',
                'phone_no' => '082311111',
                'address' => 'Solo',
                'join_date' => '2022-07-04',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300012',
                'city' => 'Sragen',
                'employee_id' => 'JR20220101102',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 2,
                'branch_id' => 1,
                'department_id' => 2,
                'referral_id' => NULL,
                'birth_place' => 'Solo',
                'birth_date' => '2022-07-10',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            4 => 
            array (
                'id' => 33,
                'name' => 'Fist Karl-Terapist',
                'email' => 'fist@gmail.com',
                'username' => 'pass123',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hv3IVYi39yFzGYmh3Th8KeuHaIRbKS/NHrL3QrypF46oOWYXFPy9a',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 08:48:31',
                'updated_at' => '2022-07-30 08:48:31',
                'phone_no' => '0813453211',
                'address' => 'Medan',
                'join_date' => '2022-07-17',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Medan',
                'employee_id' => '2011010022',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 2,
                'branch_id' => 1,
                'department_id' => 2,
                'referral_id' => 14,
                'birth_place' => 'Medan',
                'birth_date' => '2022-04-17',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            5 => 
            array (
                'id' => 5,
                'name' => 'User-HR',
                'email' => 'hr@gmail.com',
                'username' => 'user-hr',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-07-06 14:26:35',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2021-01-01',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '3524111233144330001',
                'city' => 'JAKARTA',
                'employee_id' => '20210101HR',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'user-13.jpg',
                'job_id' => 5,
                'branch_id' => 1,
                'department_id' => 4,
                'referral_id' => 1,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            6 => 
            array (
                'id' => 29,
                'name' => 'John Doe-Terapist',
                'email' => 'johndoe@gmail.com',
                'username' => 'johndoe',
                'email_verified_at' => NULL,
                'password' => '$2y$10$D8C5.ba4RGNeN9Q6uH82HeAm0P6S5jp.Y6e5IK11hypYnOByDW0rS',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 07:29:53',
                'updated_at' => '2022-07-30 07:56:32',
                'phone_no' => '085746879090',
                'address' => 'Pekanbaru',
                'join_date' => '2022-05-22',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Pekanbaru',
                'employee_id' => 'JD2022073001',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 2,
                'branch_id' => 2,
                'department_id' => 2,
                'referral_id' => 3,
                'birth_place' => 'Suwoko',
                'birth_date' => '2020-12-28',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            7 => 
            array (
                'id' => 2,
                'name' => 'User-Kasir',
                'email' => 'kasir@gmail.com',
                'username' => 'user-kasir',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-08-21 04:21:09',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2019-05-01',
                'join_years' => 3,
                'gender' => 'Female',
                'netizen_id' => '35241112331443300012',
                'city' => 'JAKARTA',
                'employee_id' => '20210101KSR',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'draft_netizen.jpg',
                'job_id' => 1,
                'branch_id' => 2,
                'department_id' => 2,
                'referral_id' => 1,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'Contract',
                'active' => 1,
            ),
            8 => 
            array (
                'id' => 53,
                'name' => 'Fake Hokis-Terapist',
                'email' => 'dada@gmill.com',
                'username' => 'Faaee',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AcOnNDUrWd/nha4KRSySa.i2OiFXR4PP.UBjc4LWjQSLnwuhbCcAm',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 11:33:55',
                'updated_at' => '2022-07-30 11:33:55',
                'phone_no' => '085746879090',
                'address' => 'Lamongan',
                'join_date' => '2022-07-10',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Lamongan',
                'employee_id' => 'HK022133',
                'photo' => '0769c4c63be92e17c0bf06d131baca96.png',
                'photo_netizen_id' => 'eddac66b535aa161c61b06d77f26b5e0.jpg',
                'job_id' => 2,
                'branch_id' => 2,
                'department_id' => 2,
                'referral_id' => 1,
                'birth_place' => 'Jakarta',
                'birth_date' => '2022-07-11',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            9 => 
            array (
                'id' => 54,
                'name' => 'Coach-Andy',
                'email' => 'trainer@gmail.com',
                'username' => 'trainer',
                'email_verified_at' => NULL,
                'password' => '$2y$10$NeF32GFPD7LysV2ggx9OROXX0XuZorwFM9kxlSu8WGZtFnTljTmqG',
                'remember_token' => NULL,
                'created_at' => '2022-08-20 11:30:05',
                'updated_at' => '2022-08-20 11:30:05',
                'phone_no' => '085746879090',
                'address' => 'Lamongan',
                'join_date' => '2022-08-01',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Lamongan',
                'employee_id' => 'TR-ADY-001',
                'photo' => '804e42dadef82ee18bcbf174a3ad9090.png',
                'photo_netizen_id' => 'b8074bdb86f8572480601bf1cd2a42ad.jpg',
                'job_id' => 7,
                'branch_id' => 1,
                'department_id' => 9,
                'referral_id' => NULL,
                'birth_place' => 'Test',
                'birth_date' => '2022-08-09',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            10 => 
            array (
                'id' => 31,
                'name' => 'Johny Deep-Terapist',
                'email' => 'serang@gmail.com',
                'username' => 'johnydeep',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZfgXjRK5S86XP2cJtmA6QOku/.v9jSEHfOIBxsZDmCAkKFTLA/MRW',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 08:03:28',
                'updated_at' => '2022-07-30 08:03:51',
                'phone_no' => '0844312333',
                'address' => 'Serang',
                'join_date' => '2015-07-18',
                'join_years' => 7,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Banten',
                'employee_id' => 'JD202204011',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 2,
                'branch_id' => 2,
                'department_id' => 2,
                'referral_id' => NULL,
                'birth_place' => 'Serang',
                'birth_date' => '2020-04-19',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            11 => 
            array (
                'id' => 30,
                'name' => 'Mark Karl-Terapist',
                'email' => 'maxkarl@gmail.com',
                'username' => 'karlmax',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Ohj/K.hR2an/GZWn0ONjMe/xd02ZbPniiDcDkY6EcVr8smyPZMhHG',
                'remember_token' => NULL,
                'created_at' => '2022-07-30 08:00:11',
                'updated_at' => '2022-07-30 08:07:59',
                'phone_no' => '081323',
                'address' => 'Lamongan',
                'join_date' => '2016-07-18',
                'join_years' => 6,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Lamongan',
                'employee_id' => 'MK20220102',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => NULL,
                'job_id' => 2,
                'branch_id' => 3,
                'department_id' => 2,
                'referral_id' => 27,
                'birth_place' => 'Lamongan',
                'birth_date' => '2022-07-04',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            12 => 
            array (
                'id' => 4,
                'name' => 'User-Admin Keuangan',
                'email' => 'finance@gmail.com',
                'username' => 'user-finance',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-07-30 08:27:49',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2022-01-01',
                'join_years' => 1,
                'gender' => 'Male',
                'netizen_id' => '3524111233144330001',
                'city' => 'JAKARTA',
                'employee_id' => '20210101ADU',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'draft_netizen_01.jpg',
                'job_id' => 4,
                'branch_id' => 1,
                'department_id' => 3,
                'referral_id' => NULL,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'User-Terapist',
                'email' => 'terapist@gmail.com',
                'username' => 'user-terapist',
                'email_verified_at' => NULL,
                'password' => '$2y$10$wYGHsVtIPTpaFqJ9w1kQReUW1xjk14eUZbPDemq9Yz5qNuwdOj1Ta',
                'remember_token' => NULL,
                'created_at' => '2022-05-28 12:40:11',
                'updated_at' => '2022-06-11 12:06:30',
                'phone_no' => '6285746879090',
                'address' => 'JALAN JAKARTA',
                'join_date' => '2017-01-01',
                'join_years' => 5,
                'gender' => 'Male',
                'netizen_id' => '3524111233144330001',
                'city' => 'JAKARTA',
                'employee_id' => '20210101TRP',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'user-13.jpg',
                'job_id' => 2,
                'branch_id' => 1,
                'department_id' => 2,
                'referral_id' => 5,
                'birth_place' => 'JAKARTA',
                'birth_date' => '2022-01-01',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
            14 => 
            array (
                'id' => 27,
                'name' => 'UserTerapist_2',
                'email' => 'yogiektambakboyo@gmail.com',
                'username' => 'userterapist2',
                'email_verified_at' => NULL,
                'password' => '$2y$10$KUxgpNxhdNzyGOxkrjvsJ.e6Pm264gbZC7roqsC4nru/ALpI28PS.',
                'remember_token' => NULL,
                'created_at' => '2022-07-25 11:46:21',
                'updated_at' => '2022-07-30 08:28:42',
                'phone_no' => '085746879090',
                'address' => 'Lamongan',
                'join_date' => '2018-07-18',
                'join_years' => 4,
                'gender' => 'Male',
                'netizen_id' => '35241112331443300021',
                'city' => 'Lamongan',
                'employee_id' => '20210021UU',
                'photo' => 'user-13.jpg',
                'photo_netizen_id' => 'draft_netizen_01.jpg',
                'job_id' => 2,
                'branch_id' => 1,
                'department_id' => 2,
                'referral_id' => 26,
                'birth_place' => 'Jakarta',
                'birth_date' => '2022-07-10',
                'employee_status' => 'On Job Training',
                'active' => 1,
            ),
        ));
        
        
    }
}